{
	"name": "chainable-error",
	"version": "1.0.0",
	"description": "Error chain like in Java world",
	"main": "index.js",
	"repository": {
		"type": "git",
		"url": "git://github.com/Crazymax11/chainable-error.git"
	},
	"dependencies": {
		"util.inherits": "^1.0.3"
	},
	"devDependencies": {
		"babel-cli": "^6.26.0",
		"babel-core": "^6.26.3",
		"babel-eslint": "^8.2.3",
		"babel-plugin-transform-builtin-extend": "^1.1.2",
		"babel-preset-env": "^1.7.0",
		"chai": "^4.1.2",
		"eslint": "^4.9.0",
		"eslint-config-airbnb-base": "12.1.0",
		"eslint-plugin-import": "^2.7.0",
		"mocha": "^5.0.4"
	},
	"scripts": {
		"test": "mocha test"
	},
	"license": "MIT"
}
